// The API contract's types: the request bodies and replies of the routes runway/server/contract.py covers.
// Generated by tools/api_contract.py from docs/openapi.json (`make api-contract`); don't edit by hand.
// lib/contract.ts's apiCall() types a call by its route, as Endpoints names it: apiCall<"GET /api/budget">(address).

/**
 * A row of GET /api/accounts: the account, its Plaid link, and (cards) its statements and how it's paid, (loans)
 * its terms.
 */
export interface AccountItem {
  id: string;
  name: string;
  display_name: string | null;
  org: string | null;
  currency: string | null;
  balance: number | null;
  available: number | null;
  balance_date: string | null;
  kind: string | null;
  pay_from: string | null;
  owed_positive: number | null;
  in_forecast: number | null;
  hidden: number | null;
  networth_hidden: number | null;
  owner: string | null;
  provider: string | null;
  plaid_account_id: string | null;
  provider_since: string | null;
  logo: string | null;
  interest_rate: number | null;
  monthly_payment: number | null;
  plaid_link: PlaidLink | null;
  statement?: PlaidStatement | EnteredStatement | null;
  statements?: ManualStatement[];
  pay_mode?: "full" | "minimum" | "fixed";
  pay_amount?: number | null;
  apr?: number | null;
  issuer_apr?: number | null;
  loan?: LoanTerms;
}

export interface BrandChoice {
  brand: string;
  bank_name: string;
  using: "brand" | "bank";
}

/**
 * A category's month on the Budget page: what's been spent (its subcategories included) against its budget, if it
 * has one. An income category's row has the same shape: `budget` is what's expected in, `spent` what has come.
 * `budget` is the month's: its own amount (`month_budget`, set for that month only) when it has one, else the
 * budget's usual amount (`usual_budget`, every other month's).
 */
export interface BudgetCategory {
  name: string;
  parent: string | null;
  path: string[];
  depth: number;
  top: string;
  has_children: boolean;
  budget: number | null;
  usual_budget: number | null;
  month_budget: number | null;
  pay_with: string | null;
  rollover_from: string | null;
  carried: number;
  available: number | null;
  usual_account: string | null;
  spent: number;
  own_spent: number;
  left: number | null;
  expected: number;
}

/** GET /api/budget?month=YYYY-MM. */
export interface BudgetMonth {
  month: string;
  days_in_month: number;
  day: number;
  categories: BudgetCategory[];
  income: number;
  income_rows: BudgetCategory[];
  uncategorized: number;
  pay_accounts: PayAccount[];
}

/** POST /api/budget's reply: the parents' budgets raised to cover their subcategories' (after an amount was saved). */
export interface BudgetSaved {
  ok: boolean;
  raised?: RaisedBudget[];
}

/**
 * POST /api/budget: a category's budget (an empty or zero amount removes it), or whether it rolls over, or (kept
 * for a release) the account it's paid with. With `month` ("YYYY-MM"), the budget's own amount for that month only
 * (it needs a budget already): an empty amount takes the month back to the usual amount, 0 budgets nothing then.
 */
export interface BudgetSet {
  category: string;
  amount?: number | string | null;
  month?: string;
  rollover?: boolean;
  pay_with?: string | null;
}

/**
 * A suggested monthly budget for a category (domain/budget_suggest.py): the larger of its typical month and the
 * recurring payments coming in the budget's month, rounded up. `budget` is the category's budget now, if it has one.
 */
export interface BudgetSuggestion {
  category: string;
  suggested: number;
  typical: number;
  recurring: number;
  budget: number | null;
}

/**
 * GET /api/budget/suggestions?month=YYYY-MM: the suggestions, and what they're from: the full months of history
 * looked at (`months`, from `first` to `last`) and the month whose recurring payments count (`recurring_month`: the
 * month asked for when it's still to come, else next month; never past the forecast's reach).
 */
export interface BudgetSuggestions {
  months: number;
  first: string | null;
  last: string | null;
  recurring_month: string;
  suggestions: BudgetSuggestion[];
}

/** The latest card statement you entered, whether a newer one should have been by now, and when the next closes. */
export interface EnteredStatement {
  source: "manual";
  closed: string;
  due: string | null;
  balance: number | null;
  minimum: number | null;
  stale: boolean;
  next_close: string;
}

/** A loan's terms (loans.terms): `rate` (annual %) and `payment` are what's used, and where they came from. */
export interface LoanTerms {
  rate: number | null;
  payment: number | null;
  maturity: string | null;
  source: "plaid" | "manual" | "inferred" | null;
  plaid: boolean;
  plaid_payment: boolean;
  set_rate: number | null;
  set_payment: number | null;
  inferred_payment: number | null;
}

/**
 * A single-use challenge (base64url) for this session, the relying party's ID (Runway's host), and for an unlock,
 * the passkey to use.
 */
export interface LockChallenge {
  challenge: string;
  rp_id: string;
  credential_id: string | null;
}

/** POST /api/lock/challenge: a challenge for turning the lock on (register) or unlocking. */
export interface LockChallengeAsk {
  purpose: "register" | "unlock";
}

/** POST /api/lock/settings: how long away locks it (seconds: 0, 60, 300 or 900). */
export interface LockIdle {
  idle: number;
}

/**
 * POST /api/lock/key-share (no body), right after an unlock or turning the lock on: this device's share of its
 * on-device cache's key, 32 random bytes as base64url (no padding), the same each time until the device's lock ends,
 * and until when the device may keep using its own copy of it without asking again (whole seconds since the epoch,
 * by the server's clock: the time of this reply plus applock.SHARE_WINDOW, 72 hours).
 */
export interface LockKeyShare {
  share: string;
  expires: number;
}

/** POST /api/lock/register: the passkey navigator.credentials.create made, all base64url, and when to lock. */
export interface LockRegister {
  credential_id: string;
  client_data: string;
  authenticator_data: string;
  public_key: string;
  alg: number;
  idle: number;
}

/**
 * This signed-in device's app lock: whether it can have one (sign-in is on), whether it's on, whether it's locked
 * now, how long away locks it (seconds: 0, 60, 300 or 900), its passkey's id (base64url) and the device's id (dev_...).
 */
export interface LockStatus {
  available: boolean;
  on: boolean;
  locked: boolean;
  idle: number;
  credential_id: string | null;
  device_id: string | null;
}

/** POST /api/lock/unlock: navigator.credentials.get's answer to the unlock challenge, all base64url. */
export interface LockUnlock {
  credential_id: string;
  client_data: string;
  authenticator_data: string;
  signature: string;
}

/** A card statement you entered (statements.history_of). */
export interface ManualStatement {
  statement_date: string;
  balance: number;
  due_date: string;
  minimum_payment: number | null;
  entered_at: string | null;
}

export interface Ok {
  ok: boolean;
}

/** The store order a charge paid for (or a refund came from). */
export interface OrderSummary {
  order_id: string;
  charge_id: string;
  retailer: string;
  order_number: string;
  channel: string | null;
  items: number;
}

export interface PayAccount {
  id: string;
  name: string;
  kind: string | null;
}

/**
 * The Plaid connection an account is matched to: its bank, the account's last digits, whether it brings
 * transactions, its latest statement's close and due dates, and the note Plaid's statements carry.
 */
export interface PlaidLink {
  institution: string | null;
  mask: string | null;
  transactions: boolean;
  closed: string | null;
  due: string | null;
  statement_note: string | null;
}

/** A card's statement from Plaid (the forecast uses it over one you entered). */
export interface PlaidStatement {
  source: "plaid";
  institution: string | null;
  closed: string;
  due: string | null;
  balance: number | null;
  minimum: number | null;
}

export interface RaisedBudget {
  category: string;
  amount: number;
}

export interface Split {
  id: number;
  amount: number;
  category: string | null;
  note: string | null;
}

/** Under a category filter, a split transaction's parts in that category (or its subcategories). */
export interface SplitMatch {
  amount: number;
  categories: string[];
}

/** A row of GET /api/transactions. */
export interface Tx {
  id: string;
  account_id: string;
  posted: string;
  amount: number;
  description: string | null;
  payee: string | null;
  category: string | null;
  category_source: string | null;
  confidence: number | null;
  needs_review: number | null;
  pending: number | null;
  recurring_id: number | null;
  is_split: number | null;
  recurring_linked_by: "you" | "auto" | null;
  notes: string | null;
  bank_posted: string | null;
  bank_amount: number | null;
  account_name: string | null;
  recurring_name: string | null;
  splits: Split[];
  match?: SplitMatch;
  retail: OrderSummary | null;
  logo: string | null;
  logo_account: string | null;
  brand: BrandChoice | null;
  source: "manual" | "plaid" | "simplefin";
}

export interface TxCreated {
  ok: boolean;
  id: string;
}

/**
 * GET /api/transactions: a page of them, how many match in all, what they add up to, and (under a category filter)
 * the category and its subcategories.
 */
export interface TxList {
  items: Tx[];
  total: number;
  sum: number;
  family?: string[];
}

/** POST /api/transactions: a transaction added by hand. `amount` is positive for money in. */
export interface TxNew {
  account: string;
  posted: string;
  payee: string;
  amount: number | string;
  category?: string | null;
  notes?: string | null;
}

/** Each covered route ("METHOD /path", as in runway/server/routes.py): what it takes and what it answers. */
export interface Endpoints {
  "GET /api/accounts": { body: never; reply: AccountItem[] };
  "GET /api/transactions": { body: never; reply: TxList };
  "POST /api/transactions": { body: TxNew; reply: TxCreated };
  "DELETE /api/transactions/{id}": { body: never; reply: Ok };
  "GET /api/lock": { body: never; reply: LockStatus };
  "DELETE /api/lock": { body: never; reply: LockStatus };
  "POST /api/lock/challenge": { body: LockChallengeAsk; reply: LockChallenge };
  "POST /api/lock/register": { body: LockRegister; reply: LockStatus };
  "POST /api/lock/unlock": { body: LockUnlock; reply: LockStatus };
  "POST /api/lock/engage": { body: never; reply: LockStatus };
  "POST /api/lock/settings": { body: LockIdle; reply: LockStatus };
  "POST /api/lock/key-share": { body: never; reply: LockKeyShare };
  "GET /api/budget": { body: never; reply: BudgetMonth };
  "POST /api/budget": { body: BudgetSet; reply: BudgetSaved };
  "GET /api/budget/suggestions": { body: never; reply: BudgetSuggestions };
}
